program: sourcecode.cpp 
	g++ sourcecode.cpp -o main 
	./main



clean:
	rm main 

# TARGET = myprogram
# SOURCES = sourcecode.cpp

# $(TARGET): $(SOURCES)
#     g++ $(SOURCES) -o $(TARGET)

# clean:
#     rm -f $(TARGET) *.o